In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [1]:
import numpy

## alias naming so numpy will be np going foward

In [2]:
import numpy as np

##syntax

In [5]:
test1=np.array([4,5,6,7])

In [6]:
type(test1)

numpy.ndarray

## array and test are methods hence () a list is enclosed [] so pasing the list to an array nd dimentional of the array

In [7]:
## to confirm the number of dimetions
test1.ndim

1

In [8]:
##to know number of rows and colums of the data
test1.shape

(4,)

In [9]:
##size of your data
test1.size

4

##2d array

In [10]:
##a 2d cause it has rows and columns
np.array([[1,2,3,4],[15,6,7,8],[4,5,6,2]])

array([[ 1,  2,  3,  4],
       [15,  6,  7,  8],
       [ 4,  5,  6,  2]])

In [11]:
##giving a variable
array2d=np.array([[1,2,3,4],[15,6,7,8],[4,5,6,2]])

In [12]:
array2d.size

12

In [13]:
array2d.shape

(3, 4)

In [14]:
array2d.ndim

2

##Acessing arrays

In [5]:
test=np.array([1,2,3,4,5,6,7,8,9,10])

In [8]:
#retrive element 1
test[0]

1

In [9]:
test[9]

10

In [10]:
test[-10]
#1 is equal to 0 and in reverse is -10 using a negative index

1

##accessing 2d arrays

In [11]:
array2d=np.array([[1,2,3,4],[5,6,7,8]])

In [12]:
array2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
array2d.size
#no of elements in the array

8

In [14]:
#[rows,clomuns] firstrow across is 0
array2d[0,0]

1

In [15]:
array2d[0,1]

2

##slicing an array

In [4]:
oned = np.array([10,20,30,34,40,40,70,40,60,80])

In [5]:
oned

array([10, 20, 30, 34, 40, 40, 70, 40, 60, 80])

In [20]:
oned[0:3] ## will stop at34 which is 3 and everything before that

array([10, 20, 30])

In [21]:
oned[5:] ## last five

array([40, 70, 40, 60, 80])

In [23]:
oned[-5:-1]

array([40, 70, 40, 60])

In [24]:
oned[:5] ## first five

array([10, 20, 30, 34, 40])

In [25]:
oned[:]

array([10, 20, 30, 34, 40, 40, 70, 40, 60, 80])

In [6]:
oned[-10]

10

In [7]:
oned[2:]

array([30, 34, 40, 40, 70, 40, 60, 80])

##2D SLICING

In [11]:
twod = np.array([[1,2,3,4],[6,7,8,9]])
twod

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [16]:
##row column
## one can slice only the rows aor the columns
twod[1, 0:3]

array([6, 7, 8])

In [18]:
## retrive element 2 and 7 
twod[0:2,1]  ## 0:2 all rows accross and one since its in the one column

array([2, 7])

In [20]:
##all elemennts in the first row
twod[0,0:4]       ##0 is the row accross and 0:4 each and every column  get what they are sharing and slice

array([1, 2, 3, 4])

## Random number generation

##Random number generator

In [4]:
np.random.randint(1,40) ##random is a function

5

In [6]:
z=np.random.randint(50,size=10) ##the size

z

In [8]:
##generate random number between 20 to 42
y=np.random.randint(20,42)

In [12]:
y

33

In [13]:
np.random.randint(20,42,size=5)

array([22, 25, 36, 29, 24])

## arange

In [15]:
## creates a numbe in s aspecific range
np.arange(29,300)

array([ 29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184,
       185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197,
       198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 20

## Reshaping used to give a new shape to an array without chaning its content

In [22]:
## or transposing (T) or two by five
x= np.array([10,11,12,13,14,15,16,17,18,19])


In [24]:
x.size


10

In [25]:
x.reshape((2,5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## where

In [26]:
##returns and index that gives you a match
dataset= np.array([10,20,30,40,50,30,20])

In [27]:
dataset

array([10, 20, 30, 40, 50, 30, 20])

In [28]:
np.where(dataset==30) ## the index of the array

(array([2, 5]),)

In [29]:
dataset=np.where(dataset>23)

##dataset greater than smaller than

In [31]:
## using sum

In [33]:
a = np.array ([[1,2,3,4],[6,7,8,9]])
a

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [34]:
a.sum()

40

In [36]:
a.mean()

5.0

In [37]:
a.std()

2.7386127875258306

In [38]:
a.var()

7.5

In [40]:
##axis=0 rows
a.sum(axis=0)

array([ 7,  9, 11, 13])

In [41]:
##axis=1 colums
a.sum(axis=1)

array([10, 30])

## Merge or concatinate data eg data in feb and jan

In [43]:
np.concatenate((a,dataset),axis=0) ## axis 0 is adding along the rows ...below

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [2, 3, 4, 5]])